In [1]:
import tensorflow as tf

In [2]:
graph1 = tf.Graph()

In [3]:
with graph1.as_default():
    a = tf.constant([2] , name = "constant_a")
    b = tf.constant([1] , name = "constant_b")

In [4]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [7]:
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


In [11]:
with graph1.as_default():
    c = tf.add(a,b)
    
sess = tf.Session(graph = graph1)
result = sess.run(c)
print(result)
sess.close()

[3]


In [15]:
graph2 = tf.Graph()

with graph2.as_default():
    Scalar = tf.constant([2])
    Vector = tf.constant([1,2,3])
    Matrix = tf.constant([ [1,2,3],[2,4,6],[4,8,12] ])
    Tensor = tf.constant([ [[1,1,1],[2,2,2],[3,3,3]],[[4,4,4],[5,5,5],[6,6,6]],[[7,7,7],[8,8,8],[9,9,9]] ])
    
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 [2] 

Vector (3 entries) :
 [1 2 3] 

Matrix (3x3 entries):
 [[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]] 

Tensor (3x3x3 entries) :
 [[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]

 [[7 7 7]
  [8 8 8]
  [9 9 9]]] 



In [19]:
print(Scalar.shape)
print(Vector.shape)
print(Matrix.shape)
print(Tensor.shape)

(1,)
(3,)
(3, 3)
(3, 3, 3)


In [6]:
graph3 = tf.Graph()
with graph3.as_default():
    mat1 = tf.constant([ [1,2,3], [4,5,6], [7,8,9]])
    mat2 = tf.constant([ [2,4,8], [3,6,9], [4,8,12] ])
    add1 = tf.add(mat1,mat2)
    add2 = mat1 + mat2
    
with tf.Session(graph = graph3) as sess:
    result = sess.run(add1)
    print(result)
    result = sess.run(add2)
    print(result)

[[ 3  6 11]
 [ 7 11 15]
 [11 16 21]]
[[ 3  6 11]
 [ 7 11 15]
 [11 16 21]]


In [7]:
with graph3.as_default():
    mult1 = tf.matmul(mat1,mat2) #multiply two matrices
    mult2 = mat1 * mat2 #multiply element by element
    
with tf.Session(graph = graph3) as sess:
    result = sess.run(mult1)
    print(result)
    result = sess.run(mult2)
    print(result)

[[ 20  40  62]
 [ 47  94 149]
 [ 74 148 236]]
[[  2   8  24]
 [ 12  30  54]
 [ 28  64 108]]


In [2]:
v = tf.Variable(0)
update = tf.assign(v,v+1)
init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(v))
    for _ in range(3):
        sess.run(update)
        print(sess.run(v))


0
1
2
3


In [4]:
a = tf.placeholder(tf.float32)
b = a*2

with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print(result)

7.0


In [5]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]
